spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BusinessManager
    username: sayari
    password: sayari
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 465
    username: sayarim558@gmail.com
    password: gcvp dlux hezi qxdw
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
        starttls:
          enable: true
    protocol: smtp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/BusinessManager"



springdoc:
  default-produces-media-type: application/json

server:
  port: 8020
keycloak:
  auth-server-url: http://localhost:9090
  realm: BusinessManager
  adminClientId: admin-cli
  adminClientSecret: x8naCRaX05NrRjhPiCtFv8vnRUfvoLfo




keycloak-admin:
  username: admin
  password: admin


spring.batch.jdbc.initialize-schema: always